### ISSUE TITLE
If settings.paginate.itemsPerPage is empty there is no output

### ISSUE THREAD

**Issue by Teisi** [BastianBalthasarBux/tt_address#3]
I see there is a error handling but i have no output in FE or BE if i have itemsPerPage = 0.

" throw new \RuntimeException('The itemsPerPage is 0 which is not allowed. Please also add "itemsPerPage" to the TS setting settings.overrideFlexformSettingsIfEmpty!', 1400741142);
"

respectively

I have no output in FE if itemsPerPage = 0.
My workaround is to add a if (in list.html):

<f:if condition="{settings.paginate.itemsPerPage}">

Feature request:
Can you set a default for this itemsPerPage directly for the content element in the BE?

**Comment by BastianBalthasarBux** [comment]
i'll have a look at it. thanks for reporting!

**Comment by BastianBalthasarBux** [comment]
Hmm, I only partly reproduce.
By default, if the field itemsPerPage in Backend is EMPTY, the TypoScript settings are going to be applied, which defaults to 15.
See also in setup.ts linke settings.overrideFlexformSettingsIfEmpty = overrideFlexformSettingsIfEmpty = paginate.itemsPerPage, singlePid, recursive

If I enter a zero, yes then there is some exception thrown.
Well, I am not sure, what we should do then, instead throwing some exception.
I cannot go further within the pagination viewhelper, than that point, because we would simply run into a division by zero ... ;)

**Comment by BastianBalthasarBux** [comment]
Should be resolved, as we switched to TYPO3 core pagination.
If there are still problems, please look at the original repo, as we finally could merge and publish tt_address v 4.0
